backend:
    name: "git-gateway"
    commit_messages:
        create: 'chore: create {{collection}} "{{slug}}"'
        update: 'chore: update {{collection}} "{{slug}}"'
        delete: 'chore: delete {{collection}} "{{slug}}"'
        uploadMedia: '[skip ci] chore: upload "{{path}}"'
        deleteMedia: '[skip ci] chore: delete "{{path}}"'
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
    - name: "categories"
      identifier_field: "name"
      label: "Categories"
      label_singular: "Category"
      folder: "content/categories"
      create: true
      editor:
          preview: false
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
    - name: "attributes"
      identifier_field: "name"
      label: "Attributes"
      label_singular: "Attribute"
      folder: "content/attributes"
      create: true
      editor:
          preview: false
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Options"
            name: "options"
            widget: "list"
    - name: "products"
      identifier_field: "name"
      label: "Products"
      label_singular: "Product"
      folder: "content/products"
      create: true
      editor:
          preview: false
      fields:
          - label: "Nome"
            name: "name"
            widget: "string"
          - label: "Images"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Attributes"
            name: "attributes"
            widget: "relation"
            collection: "attributes"
            searchFields: ["title"]
            valueField: "options"
