backend:
    name: "git-gateway"
    commit_messages:
        create: 'chore: create {{collection}} "{{slug}}"'
        update: 'chore: update {{collection}} "{{slug}}"'
        delete: 'chore: delete {{collection}} "{{slug}}"'
        uploadMedia: '[skip ci] chore: upload "{{path}}"'
        deleteMedia: '[skip ci] chore: delete "{{path}}"'
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
    - name: "categories"
      identifier_field: "name"
      label: "Categories"
      label_singular: "Category"
      folder: "src/pages/categories"
      create: true
      editor:
          preview: false
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
          - name: "type"
            widget: "hidden"
            defaultValue: "category"
          - name: "collection"
            widget: "hidden"
            defaultValue: "categories"
    - name: "attributes"
      identifier_field: "name"
      label: "Attributes"
      label_singular: "Attribute"
      folder: "content/attributes"
      create: true
      editor:
          preview: false
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Options"
            name: "options"
            widget: "list"
          - name: "type"
            widget: "hidden"
            defaultValue: "hidden"
          - name: "collection"
            widget: "hidden"
            defaultValue: "attributes"
    - name: "products"
      identifier_field: "name"
      label: "Products"
      label_singular: "Product"
      folder: "src/pages/products"
      create: true
      editor:
          preview: false
      fields:
          - label: "Nome"
            name: "name"
            widget: "string"
          - label: "Images"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Attributes"
            name: "attributes"
            widget: "relation"
            collection: "attributes"
            searchFields: ["name"]
            valueField: "name"
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "categories"
            searchFields: ["name"]
            valueField: "id"
          - name: "type"
            widget: "hidden"
            defaultValue: "product"
          - name: "collection"
            widget: "hidden"
            defaultValue: "products"
          - name: "price"
            widget: "number"
            min: 0
            step: 0.01
          - name: "currency"
            widget: "select"
            options:
                - label: "Euro"
                  value: €
