backend:
    name: git-gateway
    branch: master
    commit_messages:
        create: 'chore: create {{collection}} "{{slug}}"'
        update: 'chore: update {{collection}} "{{slug}}"'
        delete: 'chore: delete {{collection}} "{{slug}}"'
        uploadMedia: '[skip ci] chore: upload "{{path}}"'
        deleteMedia: '[skip ci] chore: delete "{{path}}"'  
media_folder: static/images
public_folder: /images
collections:
- name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Description", name: "description", widget: "text"}
        - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
        - {label: "Featured Image", name: "featuredimage", widget: image}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Tags", name: "tags", widget: "list"}
