backend:
    name: "git-gateway"
    commit_messages:
        create: 'chore: create {{collection}} "{{slug}}"'
        update: 'chore: update {{collection}} "{{slug}}"'
        delete: 'chore: delete {{collection}} "{{slug}}"'
        uploadMedia: '[skip ci] chore: upload "{{path}}"'
        deleteMedia: '[skip ci] chore: delete "{{path}}"'
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
locale: "it"
collections:
    - name: "categories"
      identifier_field: "name"
      label: "Categorie"
      label_singular: "categoria"
      folder: "src/pages/categories"
      create: true
      slug: "{{slug}}"
      editor:
          preview: false
      fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Image"
            name: "image"
            widget: "image"
          - name: "type"
            widget: "hidden"
            default: "category"
          - name: "collection"
            widget: "hidden"
            default: "categories"
    - name: "products"
      identifier_field: "name"
      label: "Prodotti"
      label_singular: "prodotto"
      folder: "src/pages/products"
      create: true
      slug: "{{slug}}"
      editor:
          preview: false
      fields:
          - label: "Nome"
            name: "name"
            widget: "string"
          - label: "Images"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Attributes"
            name: "attributes"
            widget: "list"
            fields:
                - label: "Name"
                  name: "name"
                  widget: "string"
                - label: "Options"
                  name: "options"
                  widget: "list"
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "categories"
            searchFields: ["name"]
            valueField: "name"
          - name: "type"
            widget: "hidden"
            default: "product"
          - name: "collection"
            widget: "hidden"
            default: "products"
          - name: "price"
            widget: "number"
            min: 0
            step: 0.01
