backend:
    name: git-gateway
    branch: master
media_folder: static/images/uploads
public_folder: /images/uploads
collections:
    - name: categories
      identifier_field: name
      label: Categorie
      label_singular: Categoria
      folder: content/categories
      create: true
      editor:
          preview: false
      fields:
          - label: Nome
            name: name
            widget: string
          - label: Immagine
            name: image
            widget: image
          - label: Descrizione
            name: description
            widget: text
    - name: attributes
      identifier_field: name
      label: Attributi
      label_singular: Attributo
      folder: content/attributes
      create: true
      editor:
          preview: false
      fields:
          - label: Nome
            name: name
            widget: string
          - label: Opzioni
            name: options
            widget: list
    - name: products
      identifier_field: name
      label: Prodotti
      label_singular: Prodotto
      folder: content/products
      create: true
      editor:
          preview: false
      fields:
          - label: Nome
            name: name
            widget: string
          - label: Immagine/i
            name: image
            widget: image
          - label: Descrizione
            name: description
            widget: text
          - label: Varianti
            name: variants
            widget: list
            fields:
                - label: Nome variante
                  name: variantName
                  widget: string
                - label: Scelte variante
                  name: variantChoice
                  widget: list
